# this file should be run with the command 'docker compose -f docker-compose.dev.yml up'
version: "3.9"

services:
  siri-db-dev:
    image: postgres:15.3-alpine
    container_name: siri-db-dev-c
    restart: on-failure:5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - siri-network-dev

  siri-pg-admin:
    image: dpage/pgadmin4
    container_name: siri-pg-admin-c
    restart: on-failure:5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - siri-network-dev

  siri-server-dev:
    container_name: siri-server-dev-c
    restart: on-failure:5
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    networks:
      - siri-network-dev
    command: "npm run start:dev"

  siri-client-dev:
    container_name: siri-client-dev-c
    restart: on-failure:5
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    networks:
      - siri-network-dev
    command: "npm run dev"

volumes:
  pgdata:

networks:
  siri-network-dev:
    driver: bridge
